"""anadir progreso y retornar ultimo bloque visto

Revision ID: 31b6a255f575
Revises: 72713200245b
Create Date: 2026-05-05 08:04:19.452597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31b6a255f575'
down_revision: Union[str, Sequence[str], None] = '72713200245b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_lesson_progress', sa.Column('last_block_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_lesson_progress', 'last_block_id')
    # ### end Alembic commands ###
