"""cambio en modelo de document

Revision ID: 53af13926688
Revises: 0af2bc1304a3
Create Date: 2026-05-02 14:07:56.961089

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '53af13926688'
down_revision: Union[str, Sequence[str], None] = '0af2bc1304a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('author', sa.String(length=255), nullable=True))
    op.add_column('documents', sa.Column('file_path', sa.String(length=500), nullable=False))
    op.add_column('documents', sa.Column('file_type', sa.String(length=10), nullable=False))
    op.add_column('documents', sa.Column('reading_progress', sa.Float(), nullable=False))
    op.add_column('documents', sa.Column('last_read_at', sa.DateTime(), nullable=True))
    op.add_column('documents', sa.Column('added_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.drop_column('documents', 'content')
    op.drop_column('documents', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('documents', sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('documents', 'added_at')
    op.drop_column('documents', 'last_read_at')
    op.drop_column('documents', 'reading_progress')
    op.drop_column('documents', 'file_type')
    op.drop_column('documents', 'file_path')
    op.drop_column('documents', 'author')
    # ### end Alembic commands ###
