"""agregar categoria y privacidad a los documentos

Revision ID: 72713200245b
Revises: 3fa8bc3dd105
Create Date: 2026-05-04 14:24:16.476877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72713200245b'
down_revision: Union[str, Sequence[str], None] = '3fa8bc3dd105'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('is_public', sa.Boolean(), nullable=False))
    op.add_column('documents', sa.Column('category', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'category')
    op.drop_column('documents', 'is_public')
    # ### end Alembic commands ###
